In [2]:
import pandas as pd
import numpy as np

# **Best Practice** Inisialisasi Proyek Data Analis

Kita akan **menggunakan data Location dari file Location.csv**  
Best practicenya adalah kita menggunakan copy dari file tersebut untuk dimanipulasi  
Sebisa mungkin **jangan mengubah source file secara langsung**

In [3]:
data = pd.read_csv('Location.csv', squeeze = True)
location_data = data.copy()

C:\Users\Asus\AppData\Local\Temp\ipykernel_11600\2886797464.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  data = pd.read_csv('Location.csv', squeeze = True)


#### Lalu lihat informasi 5 baris pertama dengan **.head( )** agar kita tahu sekilas isi dari file tersebut

In [4]:
location_data.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

#### Kemudian gali metadata dari file tersebut dengan **.describe( )**  

**count** = ada berapa record data di file tersebut  
**unique** = ada berapa data yang unique  
**top** = data yang paling sering muncul  
**freq** = frekuensi munculnya data top  
**Name** = nama dataset tersebut  
**dtype** = jenis dataset tersebut

In [5]:
location_data.describe()

count            1043
unique            296
top       Location 25
freq               31
Name: Location, dtype: object

# .**unique** ( ) dan .**nunique** ( )

#### **.unique** mengembalikan **array yang berisi sekumpulan data yang unique**

In [6]:
location_data.unique()

array(['Location 3', 'Location 6', 'Location 8', 'Location 26',
       'Location 34', 'Location 25', 'Location 46', 'Location 156',
       'Location 21', 'Location 13', 'Location 579', 'Location 602',
       'Location 10', 'Location 44', 'Location 30', 'Location 48',
       'Location 196', 'Location 64', 'Location 91', 'Location 62',
       'Location 75', 'Location 42', 'Location 233', 'Location 95',
       'Location 78', 'Location 61', 'Location 87', 'Location 19',
       'Location 115', 'Location 350', 'Location 377', 'Location 17',
       'Location 113', 'Location 81', 'Location 58', 'Location 212',
       'Location 53', 'Location 337', 'Location 41', 'Location 632',
       'Location 73', 'Location 214', 'Location 218', 'Location 38',
       'Location 172', 'Location 197', 'Location 101', 'Location 185',
       'Location 129', 'Location 235', 'Location 142', 'Location 50',
       'Location 76', 'Location 11', 'Location 33', 'Location 22',
       'Location 145', 'Location 203', 'Loca

In [7]:
type(location_data.unique())

numpy.ndarray

#### **.nunique** mengembalikan **jumlah data yang unique** dari dataset

In [8]:
location_data.nunique()

296

In [9]:
type(location_data.nunique())

int

# Convert **Series into Arrays**

Kita menggunakan dataset buatan sendiri yaitu ***prices_per_category***

In [10]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B' : 16600, 'Product C':15600})
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

## **.values**

Berdasarkan dokumentasi, Pandas tidak menyarankan membuat Array dengan .values  
Mereka mengarahkan kita untuk menggunakan ***.array*** dari Pandas atau ***.to_numpy*** dari NumPy 

In [11]:
prices_per_category.values

array([22250, 16600, 15600], dtype=int64)

In [12]:
type(prices_per_category.values)

numpy.ndarray

## **.array**

.array mengubah series menjadi array Pandas  
**array ini hanya bisa digunakan oleh library Pandas**

In [13]:
prices_per_category.array

<PandasArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [14]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.PandasArray

## **.to_numpy**

.to_numpy mengubah series menjadi array NumPy  
**array ini bisa digunakan di semua library** dan bisa digunakan untuk penghitungan matematika atau statistik

In [15]:
prices_per_category.to_numpy()

array([22250, 16600, 15600], dtype=int64)

In [17]:
type(prices_per_category.to_numpy())

numpy.ndarray

Dengan **.to_numpy( )** kita bisa memanipulasi data pandas  
Seperti kode dibawah, kita menggunakan index untuk mengakses valuenya lalu mengubah tipenya menjadi float 

In [18]:
test_array = prices_per_category[['Product A', 'Product B']].to_numpy(dtype='float')
test_array

array([22250., 16600.])

In [17]:
type(test_array[0])

numpy.float64

# .sort_**values**( )

In [19]:
numbers = pd.Series([15, 1000, 23, 45, 444])
numbers

0      15
1    1000
2      23
3      45
4     444
dtype: int64

Seperti namanya, fungsinya adalah sorting berdasarkan valuenya  
Secara **default argumentnya adalah ascending**

In [20]:
numbers.sort_values()

0      15
2      23
3      45
4     444
1    1000
dtype: int64

Untuk mengurutkan secara **Descending**, ubah argument **ascending menjadi False**

In [21]:
numbers.sort_values(ascending=False)

1    1000
4     444
3      45
2      23
0      15
dtype: int64

# .sort_**index**( )

Kebalikan dari sort_values, fungsi sort_index adalah sorting berdasarkan indexnya  
Secara **default argumentnya adalah ascending**

In [24]:
location_data.sort_index()

0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [25]:
location_data.sort_index(ascending=False)

1042    Location 94
1041    Location 26
1040    Location 11
1039    Location 82
1038    Location 73
           ...     
4       Location 34
3       Location 26
2        Location 8
1        Location 6
0        Location 3
Name: Location, Length: 1043, dtype: object

# Attribute dan Method **Chaining** 

Karena Python berbasis ***Object-Oriented Programming*** tentu bisa Chaining

In [26]:
location_data.index

RangeIndex(start=0, stop=1043, step=1)

In [27]:
location_data.name

'Location'

Kedua kode di atas jika digabungkan berbeda maknanya dengan kode di bawah  
Kode di bawah berarti **"kita memberi nama pada index location_data"**

In [28]:
location_data.index.name = 'Index'

In [29]:
location_data

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [30]:
location_data.index.name

'Index'

Kita bahkan bisa **mengonvert index dari location_data menjadi NumPy**

In [31]:
location_data.index.to_numpy()

array([   0,    1,    2, ..., 1040, 1041, 1042], dtype=int64)